xpcall(function ()
   local function loadModuleRaw(name: string, url: string)
      local ok, raw = pcall(game.HttpGet, game, url)
      assert(ok and type(raw) == "string", ("[%s] download failed: %s"):format(name, tostring(raw)))
      local ok2, mod = pcall(loadstring(raw))
      assert(ok2 and type(mod) == "function", ("[%s] compile failed: %s"):format(name, tostring(mod)))
      local ok3, result = pcall(mod)
      assert(ok3, ("[%s] init failed: %s"):format(name, tostring(result)))
      return result
   end
   local Eggs     = loadModuleRaw("Eggs",               "https://raw.githubusercontent.com/tnc47/B.A.Z/refs/heads/main/modules/Eggs.lua")
   local Pets     = loadModuleRaw("Pets",               "https://raw.githubusercontent.com/tnc47/B.A.Z/refs/heads/main/modules/Pets.lua")
   local Island   = loadModuleRaw("Island",             "https://raw.githubusercontent.com/tnc47/B.A.Z/refs/heads/main/modules/Island.lua")
   local Inventory= loadModuleRaw("Inventory",          "https://raw.githubusercontent.com/tnc47/B.A.Z/refs/heads/main/modules/Inventory.lua")
   local Utils    = loadModuleRaw("Utils",              "https://raw.githubusercontent.com/tnc47/B.A.Z/refs/heads/main/modules/Utils.lua")
end, print)